# Generated by Django 4.1.4 on 2022-12-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
