# Generated by Django 4.1.4 on 2022-12-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listingComments",
                to="auctions.listing",
            ),
        ),
    ]
